version: '3.8'

services:
  # Databases
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: yaai
      POSTGRES_USER: yaai_user
      POSTGRES_PASSWORD: yaai_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./infrastructure/docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  # Message Queue
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: yaai
      RABBITMQ_DEFAULT_PASS: yaai_password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # Services
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://yaai_user:yaai_password@postgres:5432/yaai
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./services/api-gateway:/app
      - /app/node_modules

  campaign-service:
    build: ./services/campaign-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://yaai_user:yaai_password@postgres:5432/yaai
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://yaai:yaai_password@rabbitmq:5672
    depends_on:
      - postgres
      - redis
      - rabbitmq
    volumes:
      - ./services/campaign-service:/app
      - /app/node_modules

  analytics-service:
    build: ./services/analytics-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - CLICKHOUSE_URL=http://clickhouse:8123
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - RABBITMQ_URL=amqp://yaai:yaai_password@rabbitmq:5672
    depends_on:
      - clickhouse
      - elasticsearch
      - rabbitmq
    volumes:
      - ./services/analytics-service:/app
      - /app/node_modules

  ai-engine:
    build: ./services/ai-engine
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://yaai_user:yaai_password@postgres:5432/yaai
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./services/ai-engine:/app
      - /app/node_modules

  # Frontend
  web-dashboard:
    build: ./apps/web-dashboard
    ports:
      - "3100:3100"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    depends_on:
      - api-gateway
    volumes:
      - ./apps/web-dashboard:/app
      - /app/node_modules

volumes:
  postgres_data:
  redis_data:
  clickhouse_data:
  elasticsearch_data:
  rabbitmq_data:

networks:
  default:
    name: yaai-network